# Generated by Django 2.0.5 on 2019-09-10 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(default='media/images/default.png', upload_to='media/images/user/',
                                            verbose_name='头像')),
                ('gender', models.PositiveSmallIntegerField(choices=[('0', '男'), ('1', '女')], default=0)),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('create_time',
                 models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('update_time',
                 models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'abstract': False,
            },
        ),
    ]
