# Generated by Django 2.0.5 on 2019-08-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/%Y/%m', verbose_name='头像'),
        ),
    ]
