# Generated by Django 2.0.5 on 2019-08-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/images/default.png', upload_to='media/images/user/', verbose_name='头像'),
        ),
    ]
