# Generated by Django 2.0.5 on 2019-09-10 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identifier',
            new_name='username',
        ),
    ]
