# Generated by Django 2.0.5 on 2019-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20190910_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=64, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supper',
            field=models.BooleanField(default=False, verbose_name='是否为管理账号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[('0', '男'), ('1', '女')], default=0, verbose_name='性别'),
        ),
    ]
