# Generated by Django 2.0.5 on 2019-09-10 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_auto_20190910_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_supper',
            new_name='is_superuser',
        ),
    ]
